### PR TITLE
Announcer simplified Chinese translations

### PR DESCRIPTION
**Pull request by chencu5958**
- This should help users in countries with simplified Chinese to understand the plugin :D

### CODE REVIEW

**Comment by TehZombiJesus** [comment]
@chencu5958 Only 1 file per pull request allowed.

**Comment by chencu5958** [comment]
> @chencu5958每个拉取请求只允许 1 个文件。

Does it mean that each translation file needs to be uploaded separately?

**Comment by TehZombiJesus** [comment]
> @chencu5958 Only 1 file per pull request allowed.

Yes.

**Comment by chencu5958** [comment]
> > @chencu5958 Only 1 file per pull request allowed.
> 
> Yes.

Ok, I have re-initiated the pull request as per above, please remember to review

**Pull request closed without merging**
