### PR TITLE
Update UltraEconomy_German.lang

### PR DESCRIPTION
**Pull request by enterih**
Added missing lines into this file (and also translated). Also some lines removed, who i couldn't find in the original file.

https://prnt.sc/1zamkpm and https://prnt.sc/1zamobg couldn't be found in any language files
+ i couldn't find any lines for "Format" "Rename" "Trade with currency" "Withdraw Currency" "Pay with Currency"

I suggest to sort the original Englishlanguage by alphabet.

### CODE REVIEW

**Comment by Fedee0** [comment]
Hi, I know they are adding the missing lines to the various plugins so maybe open a ticket and report them directly.

**Comment by enterih** [comment]
sure, i will when i find time but for now it should complete and improve the german translation. Maybe someone get an eye on it?`

**Review by TehZombiJesus — APPROVED** [review]

**Comment by TehZombiJesus** [comment]
@enterih I am currently working on adding more phrases.

I will accept your Pull Request for now but please be patient as it takes a lot of work to search all the files and make them translatable.

**Comment by enterih** [comment]
fell free to inform me if there is something new to translate

**Pull request merged**
