### PR TITLE
InsaneShops - french translation

### PR DESCRIPTION
**Pull request by Serviettesky**
Hello i have do the french translation, if you can add it that cool ^^

### CODE REVIEW

**Review by rlnt — CHANGES_REQUESTED** [review]
Please remove the spaces between the styling characters.
It has to look like this `**example**` and not like this `** example **`.

**Comment by Serviettesky** [comment]
That change somethink ???

**Comment by rlnt** [comment]
Yes, it matters or you will have multiple spaces in the game.

**Comment by Serviettesky** [comment]
Okay T>T i will change that

**Comment by rlnt** [comment]
Additionally, you have to remove the `#` symbol in front of each line.

**Comment by Serviettesky** [comment]
But there is on the base files ? that wrong ? I have chang ** m ** without space
h

**Comment by Serviettesky** [comment]
**M**

**Comment by Serviettesky** [comment]
Done

**Review by rlnt — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
