### PR TITLE
UltraEconomy_Spanish.lang

### PR DESCRIPTION
**Pull request by iKhomy**
## Issue Reference
- The UltraEconomy_English.lang file was used as a reference.

## Proposed Changes
- Corrected all the mistranslated text found in the Spanish language.

### CODE REVIEW

**Comment by TehZombiJesus** [comment]
Already translated in #156

**Comment by iKhomy** [comment]
That translation seems to be from Google Translate so several words do not make sense in Spanish, for example `LoseMoneyOnDeathFeatureView.enable.name: "Palanca"` is mistranslated. I hope you can take my translation for UltraEconomy.

**Comment by TehZombiJesus** [comment]
> That translation seems to be from Google Translate so several words do not make sense in Spanish, for example `LoseMoneyOnDeathFeatureView.enable.name: "Palanca"` is mistranslated. I hope you can take my translation for UltraEconomy.

Once I am done approving his many pull requests, feel free to review them as he uploaded them before you, I have to prioritize his.

**Comment by iKhomy** [comment]
I understand, because I just saw your translations of what the guy did and it seems that this was only used Google Translate because some things are missing translation such as `TradeSystem.createRequest.yourself: "No puedes comerciar con **yourself**" `But I will wait for the Plugin to be updated and send the request again. Thank you very much for your attention.

**Pull request closed without merging**
